Add Generic From String Method
VB10/kartal pull request #43
Opened 2023-08-08 23:09 UTC by burakJs

- Added `T? toPrimitiveFromGeneric<T>` method to String extension
- Added `string_constants` for storing string values of true and false
- Added `string_extension_mixin` for storing the utility method for converting from string to bool

2023-08-10 22:08 UTC, VB10 requested changes

2023-08-10 22:08 UTC, VB10 commented on lib/src/utility/mixin/string_extension_mixin.dart
> +    final isEqualTrueString = valueLowerCased == StringConstants.trueConstant;
true.toString();

2023-08-10 22:08 UTC, VB10 commented on lib/src/string_extension.dart
> +    if (value == null) return null;
how can we manage the list ? you can send a exception when user want to cast it

2023-08-15 22:10 UTC, VB10 requested changes

2023-08-15 22:10 UTC, VB10 commented on lib/src/string_extension.dart
> +    if (checkListFormat(T.toString())) throw const ListTypeNotSupported();
bu kod olmaz ya bool gelırse sonucta exceptıon atıyorsun adama

2023-08-16 00:19 UTC, burakJs commented on lib/src/string_extension.dart
> +    if (checkListFormat(T.toString())) throw const ListTypeNotSupported();
Hocam sadece list veya nested list oldugu zaman true diger turlu false dondugu icin sorun cikartmaz diye dusunmustum

2023-08-17 21:05 UTC, burakJs commented on lib/src/string_extension.dart
> +    if (checkListFormat(T.toString())) throw const ListTypeNotSupported();
<img width="491" alt="image" src="https://github.com/VB10/kartal/assets/70351342/1c76021b-8551-49db-b6b2-1577d0c37ed4">

2023-08-18 00:51 UTC, VB10 approved these changes

2023-08-18 00:51 UTC, merged