Localization model added to DateExtension
VB10/kartal pull request #57
Opened 2023-10-21 09:54 UTC by isshort

Hello.
This is the solution to https://github.com/VB10/kartal/pull/49 can you please check

2023-10-21 15:12 UTC, VB10 requested changes
Need to update, end please look at other extension class because i'm using ''.ext in new versions.

2023-10-21 15:12 UTC, VB10 commented on lib/src/date_extension.dart
> +extension DateTimeExtension1 on DateTime {
the name is not looking good. please update this

2023-10-21 15:12 UTC, VB10 commented on lib/src/date_extension.dart
> +        dateDifferenceModel: dateDifferenceModel ?? const DateDifferenceModel(),
verıable name is not good

currentTime and DateTime is mean like a now.

so u can change the name like a  other time or difrreance Time

2023-10-21 15:12 UTC, VB10 commented on lib/src/date_extension.dart
> +        dateTime: this,
it name will be currentTime becuase u write a extension on current

2023-10-21 15:12 UTC, VB10 commented on lib/src/date_extension.dart
> +  /// calculating the time difference. If no value is provided, the current system time will be used.
documentation is not clear, please use more understandable

2023-10-21 15:12 UTC, VB10 commented on lib/src/date_extension.dart
> +    DateTime? currentTime,
current time have to be here so please change to nullable and set to defaullt value lika a now

2023-10-21 15:12 UTC, VB10 commented on lib/src/date_extension.dart
> +  }
change to business beucase it not accaptable. For example dayDifrrence is bigger than zero, your code trying to parse every diff for each item. This need to calculate after the check business

final dayDifference = _currentTime.difference(_dateTime).inDays;
example
if(day > 0) return '';

2023-10-21 15:12 UTC, VB10 commented on lib/src/date_extension.dart
> +    return '';
if the diffrence is seconds, it can not show. Please check this

2023-10-22 07:13 UTC, isshort commented
#60

2023-10-22 07:13 UTC, closed without merging