feat: Add context focus extension for convenient keyboard handling
VB10/kartal pull request #73
Opened 2024-08-17 06:25 UTC by yusufkecer

2024-08-17 10:32 UTC, VB10 requested changes
please fix my comments, and also add unit tests with documentation in the readme

2024-08-17 10:32 UTC, VB10 commented on lib/src/private/sub_extension/context/context_focus_extension.dart
> +extension FocusExtension on BuildContext {
the usage of 'kartal' is not acceptable. You should add it in the context_general extension, and then you need to call context.general.unFocus().

2024-08-17 10:32 UTC, VB10 commented on lib/src/private/sub_extension/context/context_focus_extension.dart
> +  void get unfocus => focusScope.unfocus();
You should remove the getter because it is a function. Just call unFocus()

2024-08-17 13:04 UTC, yusufkecer commented
rebased and ready

2024-09-17 20:46 UTC, VB10 approved these changes
lgtm <3

2024-09-17 20:46 UTC, merged