New Extensions
VB10/kartal pull request #8
Opened 2021-06-02 13:27 UTC by ebrarbilgili

-EdgeInsets.zero added as paddingZero,
-Network Images added on StringExtension as NetworkImageExtension, 
-LocalizationExtension added on StringExtension, 
-warnings cleaned

2021-06-03 23:41 UTC, VB10 requested changes

2021-06-03 23:41 UTC, VB10 commented on lib/src/string_extension.dart
> +  String get locale => this.tr();
maybe it's have problem as user couldnt use easy localization and it will be not work, please back this code

2021-06-04 13:24 UTC, ebrarbilgili commented
localization is removed and it is committed

2021-06-04 20:08 UTC, VB10 requested changes

2021-06-04 20:08 UTC, VB10 commented on pubspec.yaml
> +  easy_localization: ^3.0.0
may you forget this

2021-06-04 23:40 UTC, ebrarbilgili commented on pubspec.yaml
> +  easy_localization: ^3.0.0
it should be removed in last commit

2021-06-05 21:26 UTC, merged